export const sampleLeaderboardData = [
    {
        userId: "1",
        name: "John Doe",
        avatar: "https://pbs.twimg.com/profile_images/1593304942210478080/TUYae5z7_400x400.jpg",
        email: "jhondoe234@gmail.com",
        score: 100,
        rank: 1,
    },
    {
        userId: "2",
        name: "Alice Smith",
        avatar: "https://example.com/avatar2.jpg",
        email: "alice.smith@example.com",
        score: 95,
        rank: 2,
    },
    {
        userId: "3",
        name: "Bob Johnson",
        avatar: "https://example.com/avatar3.jpg",
        email: "bob.johnson@example.com",
        score: 90,
        rank: 3,
    },
    {
        userId: "4",
        name: "Eve Wilson",
        avatar: "https://example.com/avatar4.jpg",
        email: "eve.wilson@example.com",
        score: 85,
        rank: 4,
    },
    {
        userId: "5",
        name: "Chris Brown",
        avatar: "https://example.com/avatar5.jpg",
        email: "chris.brown@example.com",
        score: 80,
        rank: 5,
    },
    {
        userId: "6",
        name: "Olivia Lee",
        avatar: "https://example.com/avatar6.jpg",
        email: "olivia.lee@example.com",
        score: 75,
        rank: 6,
    },
    {
        userId: "7",
        name: "David Davis",
        avatar: "https://example.com/avatar7.jpg",
        email: "david.davis@example.com",
        score: 70,
        rank: 7,
    },
    {
        userId: "8",
        name: "Sophia Taylor",
        avatar: "https://example.com/avatar8.jpg",
        email: "sophia.taylor@example.com",
        score: 65,
        rank: 8,
    },
    {
        userId: "9",
        name: "Michael Smith",
        avatar: "https://example.com/avatar9.jpg",
        email: "michael.smith@example.com",
        score: 60,
        rank: 9,
    },
    {
        userId: "10",
        name: "Emma Johnson",
        avatar: "https://example.com/avatar10.jpg",
        email: "emma.johnson@example.com",
        score: 55,
        rank: 10,
    },
    {
        userId: "11",
        name: "Liam Brown",
        avatar: "https://example.com/avatar11.jpg",
        email: "liam.brown@example.com",
        score: 50,
        rank: 11,
    },
    {
        userId: "12",
        name: "Ava Wilson",
        avatar: "https://example.com/avatar12.jpg",
        email: "ava.wilson@example.com",
        score: 45,
        rank: 12,
    },
    {
        userId: "13",
        name: "Noah Smith",
        avatar: "https://example.com/avatar13.jpg",
        email: "noah.smith@example.com",
        score: 40,
        rank: 13,
    },
    {
        userId: "14",
        name: "Isabella Johnson",
        avatar: "https://example.com/avatar14.jpg",
        email: "isabella.johnson@example.com",
        score: 35,
        rank: 14,
    },
    {
        userId: "15",
        name: "Mason Wilson",
        avatar: "https://example.com/avatar15.jpg",
        email: "mason.wilson@example.com",
        score: 30,
        rank: 15,
    },
    {
        userId: "16",
        name: "Ava Lee",
        avatar: "https://example.com/avatar16.jpg",
        email: "ava.lee@example.com",
        score: 25,
        rank: 16,
    },
    {
        userId: "17",
        name: "Logan Davis",
        avatar: "https://example.com/avatar17.jpg",
        email: "logan.davis@example.com",
        score: 20,
        rank: 17,
    },
    {
        userId: "18",
        name: "Amelia Taylor",
        avatar: "https://example.com/avatar18.jpg",
        email: "amelia.taylor@example.com",
        score: 15,
        rank: 18,
    },
    {
        userId: "19",
        name: "Benjamin Smith",
        avatar: "https://example.com/avatar19.jpg",
        email: "benjamin.smith@example.com",
        score: 10,
        rank: 19,
    },
    {
        userId: "20",
        name: "Charlotte Johnson",
        avatar: "https://example.com/avatar20.jpg",
        email: "charlotte.johnson@example.com",
        score: 5,
        rank: 20,
    },
];